# Generated by Django 4.2.5 on 2023-09-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='furniture_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20)),
                ('cat_picture', models.ImageField(upload_to=True)),
                ('cat_description', models.TextField()),
                ('cat_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_typename', models.CharField(choices=[('User', 'user'), ('Buyer', 'buyer'), ('Seller', 'seller'), ('Rent', 'rent')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
                ('u_dp', models.ImageField(upload_to=True)),
                ('u_gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=6)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_phone', models.BigIntegerField()),
                ('u_status', models.CharField(choices=[('0', 'Active'), ('1', 'Inactive')], max_length=1)),
                ('u_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.role')),
            ],
        ),
        migrations.CreateModel(
            name='user_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.TextField()),
                ('street_name', models.CharField(max_length=20)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_title', models.CharField(max_length=20)),
                ('f_description', models.TextField()),
                ('f_on', models.DateTimeField(auto_now_add=True)),
                ('f_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='complain_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('c_detail', models.TextField()),
                ('c_photo', models.ImageField(upload_to=True)),
                ('c_on', models.DateTimeField(auto_now_add=True)),
                ('c_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state'),
        ),
    ]
