# Generated by Django 4.2.5 on 2023-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain_details',
            name='c_photo',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='furniture_cat',
            name='cat_picture',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='u_dp',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
