# Generated by Django 4.2.5 on 2023-10-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_complain_details_c_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=20)),
                ('b_desc', models.TextField()),
                ('b_logo', models.ImageField(upload_to='photos/brand')),
            ],
        ),
        migrations.CreateModel(
            name='new_furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_name', models.CharField(max_length=20)),
                ('furniture_desc', models.TextField()),
                ('furniture_price', models.FloatField()),
                ('furniture_image', models.ImageField(upload_to='photos/furniture')),
                ('Available_qty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=20)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand_table')),
                ('furniture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.furniture_cat')),
            ],
        ),
        migrations.CreateModel(
            name='rent_furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_furniture_name', models.CharField(max_length=20)),
                ('r_furniture_desc', models.TextField()),
                ('r_furniture_price', models.FloatField()),
                ('r_furniture_image', models.ImageField(upload_to='photos/furniture')),
                ('r_Available_qty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=20)),
                ('r_brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand_table')),
                ('r_furniture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.furniture_cat')),
            ],
        ),
        migrations.CreateModel(
            name='rent_furniture_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_sartdate', models.DateField()),
                ('rent_enddate', models.DateField()),
                ('rent_furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rent_furniture')),
                ('rent_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='oldfurniture_buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_booking_datetime', models.DateTimeField(auto_now_add=True)),
                ('o_furniture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.new_furniture')),
                ('o_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='old_furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_furniture_name', models.CharField(max_length=20)),
                ('o_furniture_desc', models.TextField()),
                ('o_furniture_price', models.FloatField()),
                ('o_furniture_image', models.ImageField(upload_to='photos/furniture')),
                ('o_Available_qty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=20)),
                ('o_brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand_table')),
                ('o_furniture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.furniture_cat')),
            ],
        ),
        migrations.CreateModel(
            name='newfurniture_buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_datetime', models.DateTimeField(auto_now_add=True)),
                ('furniture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.new_furniture')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
    ]
