# Generated by Django 4.2.3 on 2024-01-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propname', models.CharField(max_length=20)),
                ('proprice', models.FloatField()),
                ('prodesc', models.TextField()),
                ('proimage', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
