# Generated by Django 4.2.3 on 2023-12-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=20)),
                ('comp_desc', models.TextField()),
                ('comp_logo', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='new_cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=10)),
                ('showroom_price', models.IntegerField()),
                ('milage_info', models.CharField(max_length=20)),
                ('passenger_capacity', models.CharField(max_length=1)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.car_category')),
                ('comp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company_table')),
            ],
        ),
        migrations.CreateModel(
            name='old_cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldcar_name', models.CharField(max_length=20)),
                ('oldcar_modelyear', models.CharField(choices=[('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4)),
                ('car_totkm', models.IntegerField()),
                ('comp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company_table')),
                ('old_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.car_category')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='rent_cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_carname', models.CharField(max_length=20)),
                ('rent_carmodelyear', models.CharField(choices=[('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4)),
                ('rent_permonth', models.IntegerField()),
                ('terms', models.TextField()),
                ('car_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.car_category')),
                ('rent_carcomp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company_table')),
            ],
        ),
        migrations.CreateModel(
            name='rent_carbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_startdate', models.DateField()),
                ('rent_enddate', models.DateField()),
                ('rentbook_datetime', models.DateTimeField(auto_now_add=True)),
                ('rent_carid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rent_cars')),
                ('rent_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='oldcar_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldbooking_datetime', models.DateTimeField(auto_now_add=True)),
                ('oldcar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.old_cars')),
                ('userbooking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='newcar_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_datetime', models.DateTimeField(auto_now_add=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.new_cars')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
    ]
