# Generated by Django 4.2.7 on 2023-11-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='a_profilepic',
            new_name='a_profile_pic',
        ),
    ]
