# Generated by Django 4.2.3 on 2024-03-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=30)),
                ('station_duration', models.IntegerField()),
                ('station_price', models.FloatField()),
            ],
        ),
    ]
