# Generated by Django 4.2.3 on 2024-03-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_duration',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_price',
            field=models.FloatField(default=3.5),
        ),
    ]
