# Generated by Django 4.2.3 on 2024-01-18 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], max_length=30)),
                ('added_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='profiles')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petxhub.login')),
            ],
        ),
    ]
