# Generated by Django 4.2.4 on 2023-08-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_detail',
            old_name='end_month',
            new_name='bank_month',
        ),
    ]
