# Generated by Django 4.2.4 on 2023-08-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_bank_month_bank_detail_end_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_address',
            old_name='b_name',
            new_name='building_name',
        ),
        migrations.AlterField(
            model_name='bank_detail',
            name='digit_no',
            field=models.CharField(max_length=12, verbose_name='Account no'),
        ),
        migrations.AlterField(
            model_name='bank_detail',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail', verbose_name='user id'),
        ),
    ]
