# Generated by Django 4.2.4 on 2023-09-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_b_name_user_address_building_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user_typename',
            field=models.CharField(choices=[('User', 'user'), ('Seller', 'seller'), ('Admin', 'admin')], max_length=10),
        ),
    ]
