# Generated by Django 4.2.6 on 2023-11-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='submit_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=20)),
                ('pLname', models.CharField(max_length=20)),
                ('pMail', models.EmailField(max_length=254)),
                ('pPhn', models.BigIntegerField()),
                ('pTrip', models.CharField(max_length=20)),
                ('pTripClass', models.CharField(max_length=20)),
                ('pStartCountry', models.CharField(max_length=20)),
                ('pEndCountryp', models.CharField(max_length=20)),
                ('pStartDate', models.CharField(max_length=20)),
                ('pEndDate', models.CharField(max_length=20)),
                ('pAirType', models.CharField(max_length=20)),
                ('pLugg', models.CharField(max_length=1)),
                ('pAirName', models.CharField(max_length=20)),
                ('pAirNum', models.CharField(max_length=20)),
                ('pAdults', models.CharField(max_length=1)),
                ('pChild', models.CharField(max_length=1)),
                ('pHotelType', models.CharField(max_length=20)),
                ('pVehicle', models.CharField(max_length=10)),
                ('pPassNum', models.CharField(max_length=20)),
                ('pPassExpNum', models.CharField(max_length=20)),
                ('pMsg', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
