# Generated by Django 5.0 on 2023-12-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insertproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pprice', models.FloatField()),
                ('pdesc', models.TextField()),
                ('pimage', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
