# Generated by Django 5.0 on 2023-12-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='insertproduct',
            new_name='insertproductdata',
        ),
    ]
